parameters:
  env: dev
  appName: 'AppName'

jobs:
- deployment: Deploy
  pool:
    vmImage: 'ubuntu-18.04'
  environment: ${{ parameters.env }}
  variables:
  - group: 'Release'
  strategy:
    runOnce:
      deploy:
        steps:
        - download: current
          artifact: drop
        - task: AzureWebApp@1
          displayName: 'Azure App Service Deploy: website'
          inputs:
            azureSubscription: 'Resource Manager - Tailspin - Space Game'
            appName: ${{ parameters.appName }}
            package: '$(Pipeline.Workspace)/drop/$(buildConfiguration)/*.zip'